---
config:
  flowchart:
    curve: linear
---
graph TD;
	__start__([<p>__start__</p>]):::first
	intake(intake)
	validate(validate)
	investigate(investigate)
	resolve(resolve)
	close(close)
	reject(reject)
	__end__([<p>__end__</p>]):::last
	__start__ --> intake;
	intake --> validate;
	investigate --> resolve;
	resolve --> close;
	validate -.-> investigate;
	validate -.-> reject;
	close --> __end__;
	reject --> __end__;
	classDef default fill:#f2f0ff,line-height:1.2
	classDef first fill-opacity:0
	classDef last fill:#bfb6fc
